export default {
  HOME: "home",
  PROFILE: "Profile",
  PROFILE_POST: "ProfilePost",
  PROFILE_BAYAN: "ProfileBayan",
  PROFILE_CHAT: "ProfileChat",
  PROFILE_UPDATE: "profileUpdate",
  SETTINGS: "Settings",
  POST: "Post",
  POSTDETAILS: "postDetails",
  BAYAN: "Bayan",
  BAYAN_POST: "bayanPost",
  CHATS: "Chats",
  CHAT: "Chat",
  LOGIN: "Login",
  SIGNUP: "Signup",
  VERIFYCODE: "verifyCode",
  FORGET: "forgetPassword",
  PARENT: "Parent",
  REACTION: "reactionDetails",
};
